import { Poppins } from "next/font/google";
import "./globals.css";
import FormatLayout from "@/src/components/FormatLayout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
        rel="stylesheet"
      />
      <body className={poppins.className}>
        <FormatLayout>{children}</FormatLayout>
      </body>
    </html>
  );
}
